IntroGatewayAPI: Fix parentRefs indentation
Fix indentation of parentRefs in example yaml.

The current examples have some indentation errors that cause "oc apply" to
fail with the following error message:

    error: error parsing STDIN: error converting YAML to JSON: yaml: line 9: did not find expected '-' indicator

This commit fixes these errors.

* docs/blogs/IntroGatewayAPI/GettingCreative.md:
* docs/blogs/IntroGatewayAPI/GettingStarted.md: Indent parentRefs
correctly.